name: unittests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  rest-api-tests:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: go test -race -tags fast -v ./...